config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin Dashboard
  namespace :admin do
    resources :categories
    resources :listings
    resources :users
    resources :profiles
    resources :roles
    resources :measurements
    root to: 'categories#index'
  end

  # Trader Dashboard
  namespace :trader do
    resources :listings
    root to: 'listings#index'
  end

  namespace :messages do
    post '/new', to: 'messages#create', as: :new
    post '/reply', to: 'messages#reply', as: :reply
    get 'conversation/:id', to: 'conversations#show', as: :conversation
    root to: 'conversations#index'
  end

  scope :profile do
    get 'edit', to: 'profiles#edit', as: :manage_profile
    put 'edit', to: 'profiles#update'
    patch 'edit', to: 'profiles#update'
    get '/:id', to: 'profiles#show', as: :profile
    get '', to: 'profiles#show', as: :own_profile
  end

  get 'users', to: 'profiles#edit'

  scope '/view' do
    get '/categories/root', to: redirect('view/categories')
    get '/categories/:id', to: 'categories#show', as: :category
    get '/categories/:cat_id/:id', to: 'items#show', as: :item
    resources :categories
    resources :listings
    root to: 'categories#index', as: :view
    get '/profile/:id', to: 'profile#show'
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # get '/moderator', to: 'static_pages#moderator', as: :moderator_root

  get '/faq', to: 'static_pages#faq', as: :faq
  get '/about', to: 'static_pages#about', as: :about

  root 'static_pages#index'
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index; end
  def faq; end
  def about; end
end

app/views/static_pages/about.html.erb
<div class="container my-5 ">
  <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg bg-primary-dark text-secondary">
    <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
      <h1 class="display-4 fw-bold lh-1">About Us</h1>
      <p class="lead">We want you to be able to trade your stuff</p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
        <%if user_signed_in? %>
          <%= link_to 'Search Listings', view_path, class:"btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
          <%= link_to 'Manage Your Listings', trader_root_path, class:"btn btn-outline-secondary btn-lg px-4" %>
        <% else %>
          <%= link_to 'Sign Up', new_registration_path(resource_name), class:"btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
          <%= link_to 'Log In', new_session_path(resource_name), class:"btn btn-outline-secondary btn-lg px-4" %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
      <%= image_tag('Market_Stall.jpg', class:"rounded-lg-3", width:'720') %>
    </div>
  </div>
</div>

app/views/static_pages/faq.html.erb
<div class="container my-5 ">
  <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg bg-primary-dark text-secondary">
    <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
      <h1 class="display-4 fw-bold lh-1">Frequent Questions</h1>
      <p class="lead">What do you need to know?</p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
        <%if user_signed_in? %>
          <%= link_to 'Search Listings', view_path, class:"btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
          <%= link_to 'Manage Your Listings', trader_root_path, class:"btn btn-outline-secondary btn-lg px-4" %>
        <% else %>
          <%= link_to 'Sign Up', new_registration_path(resource_name), class:"btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
          <%= link_to 'Log In', new_session_path(resource_name), class:"btn btn-outline-secondary btn-lg px-4" %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
      <%= image_tag('Market_Stall.jpg', class:"rounded-lg-3", width:'720') %>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="container my-5 ">
  <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg bg-primary-dark text-secondary">
    <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
      <h1 class="display-4 fw-bold lh-1">Green Marketplace</h1>
      <p class="lead">Trade your excess for what you need</p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
        <%if user_signed_in? %>
          <%= link_to 'Search Listings', view_path, class:"btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
          <%= link_to 'Manage Your Listings', trader_root_path, class:"btn btn-outline-secondary btn-lg px-4" %>
        <% else %>
          <%= link_to 'Sign Up', new_registration_path(resource_name), class:"btn btn-primary btn-lg px-4 me-md-2 fw-bold" %>
          <%= link_to 'Log In', new_session_path(resource_name), class:"btn btn-outline-secondary btn-lg px-4" %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
      <%= image_tag('market_stall.jpg', class:"rounded-lg-3", width:'720') %>
    </div>
  </div>
</div>