config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin Dashboard
  namespace :admin do
    resources :categories
    resources :listings
    resources :users
    resources :profiles
    resources :roles
    resources :measurements
    root to: 'categories#index'
  end

  # Trader Dashboard
  namespace :trader do
    resources :listings
    root to: 'listings#index'
  end

  namespace :messages do
    post '/new', to: 'messages#create', as: :new
    post '/reply', to: 'messages#reply', as: :reply
    get 'conversation/:id', to: 'conversations#show', as: :conversation
    root to: 'conversations#index'
  end

  scope :profile do
    get 'edit', to: 'profiles#edit', as: :manage_profile
    put 'edit', to: 'profiles#update'
    patch 'edit', to: 'profiles#update'
    get '/:id', to: 'profiles#show', as: :profile
    get '', to: 'profiles#show', as: :own_profile
  end

  get 'users', to: 'profiles#edit'

  scope '/view' do
    get '/categories/root', to: redirect('view/categories')
    get '/categories/:id', to: 'categories#show', as: :category
    get '/categories/:cat_id/:id', to: 'items#show', as: :item
    resources :categories
    resources :listings
    root to: 'categories#index', as: :view
    get '/profile/:id', to: 'profile#show'
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # get '/moderator', to: 'static_pages#moderator', as: :moderator_root

  get '/faq', to: 'static_pages#faq', as: :faq
  get '/about', to: 'static_pages#about', as: :about

  root 'static_pages#index'
end

app/models/listing.rb
# frozen_string_literal: true

class Listing < ApplicationRecord

  belongs_to :category
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  belongs_to :measurement
  has_many :messages, dependent: :destroy
  has_one_attached :image
  
  validates :headline, :category, :quantity, :measurement, :start_dtg, :finish_dtg, presence: true
  
  def measurement_display
    quantity > 1 ? measurement.plural : measurement.unit
  end

  def item_name
    if measurement.measurement_for == 'count'
      quantity > 1 ? category.plural : category.name
    else
      category.plural
    end
  end
end

app/controllers/admin/listings_controller.rb
# frozen_string_literal: true

module Admin
  class ListingsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/listing_controller.rb
class ListingController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def create
  end
end

app/controllers/listings_controller.rb
# frozen_string_literal: true

class ListingsController < ApplicationController
  def index; end

  def show
    @message = Message.new
    @listing = Listing.find(params[:id])
    @category = @listing.category
  end
end

app/controllers/trader/listings_controller.rb
# frozen_string_literal: true

module Trader
  class ListingsController < Trader::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    def create
      resource = resource_class.new(resource_params)
      authorize_resource(resource)
      resource.owner = current_user
      if resource.save
        redirect_to(
          after_resource_created_path(resource),
          notice: translate_with_resource('create.success')
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource)
        }, status: :unprocessable_entity
      end
    end
    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/views/listings/show.html.erb
<div class="container my-5 ">
  <div class="rounded-3 p-4 border shadow-lg bg-primary-dark text-secondary">
    <h1 class="text-secondary"><%= @listing.headline %> </h1>
    <hr>
    <div class="list-group-flush">
      <div class="list-group-item list-group-item-primary">
        <div class="row">
          <div class="col-3">
            <h5>Owner</h5>
            <%= @listing.owner.profile.display_name.capitalize %> - <%= link_to 'View Profile', profile_path(@listing.owner.profile) %>
          </div>
          <div class="col-3">
            <h5>Location</h5>
            <%= "#{@listing.owner.profile.suburb}, #{@listing.owner.profile.state}" %>
          </div>
        </div>
      </div>
      <div class="list-group-item list-group-item-primary">
        <h5>Description</h5>
        <%= "#{@listing.quantity} #{@listing.measurement_display} of #{@listing.item_name}" %>
      </div>
      <% unless @listing.owner == current_user %>
        <div class="list-group-item list-group-item-primary">
          <h5>Send <%= @listing.owner.profile.display_name.capitalize %> a message about this listing</h5>
          <%= form_with(model: @message, url: messages_new_path) do |form| %>
            <div class="row w-100 pt-3">
              <div class="col-9 form-floating text-dark">
                <% invalid = @message.errors.include?('body') %>
                <%= form.text_area :body, class:"w-100 form-control #{'is-invalid' if invalid}" %>
                <div class="form-text invalid-feedback">
                  <% @message.errors.full_messages_for('body').each do |message| %>
                    <%= message %>
                  <% end %>
                </div>
              </div>
              <div class="col-3">
                <%= form.hidden_field :listing, value: @listing.id%>
                <%= form.hidden_field :recipient, value: @listing.owner.id %>
                <%= form.submit 'Send Message', class:'form-control' %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <hr>
      <%= link_to "Return to #{@listing.category.plural}", @listing.category, class:"text-secondary" %>
    </div>
  </div>
</div>