config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin Dashboard
  namespace :admin do
    resources :categories
    resources :listings
    resources :users
    resources :profiles
    resources :roles
    resources :measurements
    root to: 'categories#index'
  end

  # Trader Dashboard
  namespace :trader do
    resources :listings
    root to: 'listings#index'
  end

  namespace :messages do
    post '/new', to: 'messages#create', as: :new
    post '/reply', to: 'messages#reply', as: :reply
    get 'conversation/:id', to: 'conversations#show', as: :conversation
    root to: 'conversations#index'
  end

  scope :profile do
    get 'edit', to: 'profiles#edit', as: :manage_profile
    put 'edit', to: 'profiles#update'
    patch 'edit', to: 'profiles#update'
    get '/:id', to: 'profiles#show', as: :profile
    get '', to: 'profiles#show', as: :own_profile
  end

  get 'users', to: 'profiles#edit'

  scope '/view' do
    get '/categories/root', to: redirect('view/categories')
    get '/categories/:id', to: 'categories#show', as: :category
    get '/categories/:cat_id/:id', to: 'items#show', as: :item
    resources :categories
    resources :listings
    root to: 'categories#index', as: :view
    get '/profile/:id', to: 'profile#show'
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # get '/moderator', to: 'static_pages#moderator', as: :moderator_root

  get '/faq', to: 'static_pages#faq', as: :faq
  get '/about', to: 'static_pages#about', as: :about

  root 'static_pages#index'
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Pundit::Authorization
    # include Administrate::Punditize
    before_action :authenticate_user!
    before_action :authorize_admin
    
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    def user_not_authorized
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_back(fallback_location: root_path)
    end

    def authorize_admin
      authorize :static_page, :admin?
    end

    
    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :check_valid_profile

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_back(fallback_location: root_path)
  end

  def check_valid_profile
    controller_exceptions = %w[profiles static_pages admin sessions registrations]

    if user_signed_in? && current_user.profile.valid? == false && controller_exceptions.include?(controller_name) == false
      flash[:alert] = "You need to complete your profile."
      redirect_to(manage_profile_path)
    end
  end
end

app/controllers/messages/application_controller.rb
module Messages
  class ApplicationController < ApplicationController
    include Pundit::Authorization
    before_action :authenticate_user!
    before_action :check_valid_profile

    rescue_from ActiveRecord::RecordNotFound, with: :user_not_authorized

    def user_not_authorized
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_back(fallback_location: trader_root_path)
    end

    def check_valid_profile
      controller_exceptions = %w[profiles static_pages admin sessions registrations]
      if user_signed_in? && current_user.profile.valid? == false && controller_exceptions.include?(controller_name) == false
        flash[:alert] = 'You need to complete your profile.'
        
        redirect_to(manage_profile_path)
      end
    end
  end
end

app/controllers/trader/application_controller.rb
# frozen_string_literal: true

# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Trader
  class ApplicationController < Administrate::ApplicationController
    include Administrate::Punditize
    before_action :authenticate_user!
    before_action :check_valid_profile
    rescue_from ActiveRecord::RecordNotFound, with: :user_not_authorized

    def user_not_authorized
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_back(fallback_location: trader_root_path)
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    def check_valid_profile
      controller_exceptions = %w[profiles static_pages admin sessions registrations]
  
      if user_signed_in? && current_user.profile.valid? == false && controller_exceptions.include?(controller_name) == false
        flash[:alert] = "You need to complete your profile."
        redirect_to(manage_profile_path)
      end
    end
  end

end

app/controllers/trader/listings_controller.rb
# frozen_string_literal: true

module Trader
  class ListingsController < Trader::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    def create
      resource = resource_class.new(resource_params)
      authorize_resource(resource)
      resource.owner = current_user
      if resource.save
        redirect_to(
          after_resource_created_path(resource),
          notice: translate_with_resource('create.success')
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource)
        }, status: :unprocessable_entity
      end
    end
    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/trader/messages_controller.rb
module Trader
  class MessagesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helpers for the entire application

module ApplicationHelper

  def active_class(path)
    if request.path == path
      'active'
    else
      ''
    end
  end

  def active_namespace(path)
    request.path.starts_with?(path) ? 'active' : ''
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end



  def flash_class(level)
    { notice: 'alert alert-info',
      success: 'alert alert-success',
      error: 'alert alert-danger',
      alert: 'alert alert-warning' }[level.to_sym]
  end
end

app/views/trader/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <% next unless value.respond_to?(:html_safe) %>
      <div class="flash flash-<%= key %>"><%= value.html_safe %></div>
    <% end -%>
  </div>
<% end %>

app/views/trader/application/_footer.html.erb
<footer class="py-3 mt-4">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
  </ul>
  <p class="text-center text-muted">&copy; 2021 Company, Inc</p>
</footer>

app/views/trader/application/_header.html.erb
<header class="row navbar navbar-dark bg-primary">
  <div class="col-3 ">
    <a class="navbar-brand text-secondary" href="">Marketplace</a>
  </div>
  <nav class="col-9 px-0">
    <div class="container-fluid">
      <div class="btn-group" flex-column flex-md-row">
        <%= link_to 'Home', root_path, class:"btn btn-secondary #{active_class(root_path)}"%>
        <%= link_to 'Browse Listings', view_path, class:"btn btn-secondary #{active_namespace(view_path)}"%>
        <%= link_to 'Trader', trader_root_path, class:"btn btn-secondary #{active_namespace(trader_root_path)}"%>
        <%= link_to 'Messages', messages_root_path, class:"btn btn-secondary #{active_namespace(messages_root_path)}"%>
        <%= link_to 'Moderator', moderator_root_path, class:"btn btn-secondary #{active_namespace(moderator_root_path)}"%>      
        <%= link_to 'Admin', admin_root_path, class:"btn btn-secondary #{active_namespace(admin_root_path)}"%>
        <%= render 'application/header_user' %>
      </div>
    </div>
  </nav>
</header>

app/views/trader/application/_header_user.html.erb
  <% if user_signed_in? %>
  <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
    <%= current_user.email%>
  </button>
  <div class="dropdown-menu dropdown-menu-end">
    <%# <div class="dropdown-divider"></div> %>
    <%= link_to 'Manage Account', manage_profile_path,class:'dropdown-item'%>
    <%= link_to 'Sign Out', destroy_user_session_path, data:{turbo_method: :delete},class:'dropdown-item'%>
  </div>
<% else %>
  <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
    Log In
  </button>
  <div class="dropdown-menu dropdown-menu-end">
    <%= form_for(resource, as: resource_name, url: session_path(resource_name),class:"px-4 py-3") do |f| %>
      <div class="field dropdown-item">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
      <div class="field dropdown-item">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "current-password" %>
      </div>
      <% if devise_mapping.rememberable? %>
        <div class="field dropdown-item">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end %>
      <div class="actions dropdown-item">
        <%= f.submit "Log in" %>
      </div>
    <% end %>
    <div class="dropdown-divider"></div>
    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
      <%= link_to "Sign up", new_registration_path(resource_name), class:'dropdown-item' %>
    <% end %>
    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name), class:'dropdown-item' %>
    <% end %>
    <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
      <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class:'dropdown-item' %>
    <% end %>
    <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
      <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class:'dropdown-item' %>
    <% end %>
    <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class:'dropdown-item', method: :post %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/trader/application/_icons.html.erb
<svg hidden xmlns="http://www.w3.org/2000/svg">
  <symbol id="icon-cancel" viewBox="0 0 48 48">
    <path fill-rule="evenodd" d="M24 19.757l-8.485-8.485c-.784-.783-2.047-.782-2.827 0l-1.417 1.416c-.777.777-.78 2.046.002 2.827L19.757 24l-8.485 8.485c-.783.784-.782 2.047 0 2.827l1.416 1.417c.777.777 2.046.78 2.827-.002L24 28.243l8.485 8.485c.784.783 2.047.782 2.827 0l1.417-1.416c.777-.777.78-2.046-.002-2.827L28.243 24l8.485-8.485c.783-.784.782-2.047 0-2.827l-1.416-1.417c-.777-.777-2.046-.78-2.827.002L24 19.757zM24 47c12.703 0 23-10.297 23-23S36.703 1 24 1 1 11.297 1 24s10.297 23 23 23z" />
  </symbol>

  <symbol id="icon-eyeglass" viewBox="0 0 48 48">
    <path d="M27.885 32.515c-2.864 1.966-6.333 3.116-10.07 3.116C7.976 35.63 0 27.656 0 17.817 0 7.976 7.976 0 17.816 0S35.63 7.976 35.63 17.816c0 3.736-1.15 7.205-3.115 10.07l14.53 14.53c1.278 1.277 1.275 3.352 0 4.628-1.28 1.278-3.353 1.278-4.63 0l-14.53-14.53zm-10.07-3.736c6.056 0 10.964-4.91 10.964-10.964 0-6.055-4.91-10.964-10.964-10.964-6.055 0-10.964 4.91-10.964 10.964 0 6.055 4.91 10.963 10.964 10.963z" />
  </symbol>

  <symbol id="icon-up-caret" viewBox="0 0 48 48">
    <path d="M2.988 33.02c-1.66 0-1.943-.81-.618-1.824l20-15.28c.878-.672 2.31-.67 3.188 0l20.075 15.288c1.316 1.003 1.048 1.816-.62 1.816H2.987z" />
  </symbol>
</svg>

app/views/trader/application/_index_header.html.erb
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>
<header class="row mt-3" role="banner">
  <h1 class="col" id="page-title">
    <%= content_for(:title) %>
  </h1>
  <div class="col">
    <% if show_search_bar %>
      <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name),
      class: 'col'
    ) %>
    <% end %>
  </div>
  <div class="col">
    <%= link_to(
      t(
        "administrate.actions.new_resource",
        name: display_resource_name(page.resource_name, singular: true).downcase
      ),
      [:new, namespace, page.resource_path.to_sym],
      class: "btn btn-primary",
    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
  </div>
</header>

app/views/trader/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.
%>

<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/trader/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="list-group-flush" role="navigation">
  <%# link_to(t("administrate.navigation.back_to_app"), root_url, class: "button button--alt button--nav") if defined?(root_url) %>

  <% Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource| %>
    <%= link_to(
      display_resource_name(resource),
      resource_index_route(resource),
      class: "list-group-item list-group-item-action list-group-item-primary p-3 px-2 #{nav_link_state(resource)}"
    ) if valid_action?(:index, resource) && show_action?(:index, model_from_resource(resource)) %>
  <% end %>
</nav>

app/views/trader/application/_search.html.erb
<form class="" role="search">
  <div class="input-group">
    <span class="input-group-text" >
      <i class="bi bi-search"></i>
    </span>
    <input class="form-control"
         id="search"
         type="search"
         name="search"
         placeholder="<%= t("administrate.search.label",
                            resource: resource_name) %>"
         value="<%= search_term %>">
    <%= link_to clear_search_params, class: "btn btn-secondary" do %>
      <i class="bi bi-x-circle"></i>
    <% end %>
  </div>
</form>

app/views/trader/application/_stylesheet.html.erb
<%#
# Stylesheet Partial

This partial imports the necessary stylesheets on each page.
By default, it includes the application CSS,
but each page can define additional CSS sources
by providing a `content_for(:stylesheet)` block.
%>

<% Administrate::Engine.stylesheets.each do |css_path| %>
  <%= stylesheet_link_tag css_path %>
<% end %>

<%= yield :stylesheet %>

app/views/trader/application/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { t("administrate.actions.edit_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.show_resource", name: page.page_title),
      [namespace, page.resource],
      class: "button",
    ) if valid_action?(:show) && show_action?(:show, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/trader/application/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<%=
  render("index_header",
    resources: resources,
    search_term: search_term,
    page: page,
    show_search_bar: show_search_bar,
  )
%>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources, param_name: '_page' %>
</section>

app/views/trader/application/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) do %>
  <%= t(
    "administrate.actions.new_resource",
    name: display_resource_name(page.resource_name).titleize
  ) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
</section>

app/views/trader/application/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "btn btn-primary",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: page.resource.class.human_attribute_name(attribute.name),
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>